# Cloud Build — triggered on every push to main.
# Builds both Docker images, deploys as canary (--no-traffic), health-checks,
# then shifts 100 % traffic. If the health check fails the step exits non-zero,
# Cloud Build marks the build failed, and the previous revision keeps serving.

substitutions:
  _REGION: us-central1
  _API_SERVICE: oryn-api
  _WEB_SERVICE: oryn-web
  _REPO: oryn
  _SA: oryn-cloudrun

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # ── 1. Build API image ──
  - id: build-api
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_API_SERVICE}:$SHORT_SHA
      - -f
      - apps/api/Dockerfile
      - .

  # ── 2. Build Web image (in parallel) ──
  - id: build-web
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_WEB_SERVICE}:$SHORT_SHA
      - -f
      - apps/web/Dockerfile
      - --build-arg
      - NEXT_PUBLIC_API_BASE_URL=https://${_API_SERVICE}-${PROJECT_NUMBER}.${_REGION}.run.app
      - .
    waitFor: ['-']  # run in parallel with build-api

  # ── 3. Push API image ──
  - id: push-api
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_API_SERVICE}:$SHORT_SHA
    waitFor: ['build-api']

  # ── 4. Push Web image ──
  - id: push-web
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_WEB_SERVICE}:$SHORT_SHA
    waitFor: ['build-web']

  # ── 5. Deploy API canary (no traffic) ──
  - id: deploy-api-canary
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - ${_API_SERVICE}
      - --project=$PROJECT_ID
      - --region=${_REGION}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_API_SERVICE}:$SHORT_SHA
      - --no-traffic
      - --tag=canary
      - --service-account=${_SA}@$PROJECT_ID.iam.gserviceaccount.com
      - --timeout=3600
      - --allow-unauthenticated
      - --set-env-vars=GOOGLE_GENAI_USE_VERTEXAI=true,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=${_REGION},CORS_ORIGIN=https://${_WEB_SERVICE}-${PROJECT_NUMBER}.${_REGION}.run.app
      - --quiet
    waitFor: ['push-api']

  # ── 6. Deploy Web canary (no traffic) ──
  - id: deploy-web-canary
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - ${_WEB_SERVICE}
      - --project=$PROJECT_ID
      - --region=${_REGION}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_WEB_SERVICE}:$SHORT_SHA
      - --no-traffic
      - --tag=canary
      - --service-account=${_SA}@$PROJECT_ID.iam.gserviceaccount.com
      - --allow-unauthenticated
      - --quiet
    waitFor: ['push-web']

  # ── 7. Health-check API canary ──
  - id: healthcheck-api
    name: gcr.io/cloud-builders/curl
    args:
      - -sSf
      - --retry
      - '4'
      - --retry-delay
      - '5'
      - --retry-all-errors
      - https://canary---${_API_SERVICE}-${PROJECT_NUMBER}.${_REGION}.run.app/health
    waitFor: ['deploy-api-canary']

  # ── 8. Health-check Web canary ──
  - id: healthcheck-web
    name: gcr.io/cloud-builders/curl
    args:
      - -sSf
      - --retry
      - '4'
      - --retry-delay
      - '5'
      - --retry-all-errors
      - https://canary---${_WEB_SERVICE}-${PROJECT_NUMBER}.${_REGION}.run.app/
    waitFor: ['deploy-web-canary']

  # ── 9. Promote API — shift 100% traffic ──
  - id: promote-api
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - services
      - update-traffic
      - ${_API_SERVICE}
      - --project=$PROJECT_ID
      - --region=${_REGION}
      - --to-latest
      - --quiet
    waitFor: ['healthcheck-api']

  # ── 10. Promote Web — shift 100% traffic ──
  - id: promote-web
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - services
      - update-traffic
      - ${_WEB_SERVICE}
      - --project=$PROJECT_ID
      - --region=${_REGION}
      - --to-latest
      - --quiet
    waitFor: ['healthcheck-web']

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_API_SERVICE}:$SHORT_SHA
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_WEB_SERVICE}:$SHORT_SHA

timeout: 1800s
