# Cloud Build — triggered on every push to main.
# Builds both Docker images, deploys as canary (--no-traffic), health-checks,
# then shifts 100 % traffic. If the health check fails the step exits non-zero,
# Cloud Build marks the build failed, and the previous revision keeps serving.

substitutions:
  _REGION: us-central1
  _API_SERVICE: oryn-api
  _WEB_SERVICE: oryn-web
  _REPO: oryn
  _SA: oryn-cloudrun

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # ── 1. Build API image ──
  - id: build-api
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_API_SERVICE}:$SHORT_SHA
      - -f
      - apps/api/Dockerfile
      - .

  # ── 2a. Resolve API URL using gcloud ──
  #    Must run in a gcloud image so the CLI is available.
  #    Writes the URL to /workspace/.api_url for the next step to consume.
  #    Fails the build immediately if the API service cannot be found — prevents
  #    a broken web image from being deployed with a guessed/wrong URL.
  - id: resolve-api-url
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        API_URL=$$(gcloud run services describe ${_API_SERVICE} \
          --project=$PROJECT_ID --region=${_REGION} \
          --format='value(status.url)' --quiet)
        if [ -z "$$API_URL" ]; then
          echo "ERROR: could not resolve URL for Cloud Run service '${_API_SERVICE}'. Aborting."
          exit 1
        fi
        echo "Resolved API URL: $$API_URL"
        echo -n "$$API_URL" > /workspace/.api_url
    waitFor: ['-']

  # ── 2b. Build Web image ──
  #    Reads the API URL written by resolve-api-url from /workspace/.api_url
  #    and bakes it into the Next.js client bundle at build time.
  - id: build-web
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        API_URL=$$(cat /workspace/.api_url)
        echo "Using API URL: $$API_URL"
        docker build \
          -t ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_WEB_SERVICE}:$SHORT_SHA \
          -f apps/web/Dockerfile \
          --build-arg NEXT_PUBLIC_API_BASE_URL=$$API_URL \
          .
    waitFor: ['resolve-api-url']

  # ── 3. Push API image ──
  - id: push-api
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_API_SERVICE}:$SHORT_SHA
    waitFor: ['build-api']

  # ── 4. Push Web image ──
  - id: push-web
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_WEB_SERVICE}:$SHORT_SHA
    waitFor: ['build-web']

  # ── 5. Deploy API canary (no traffic) ──
  - id: deploy-api-canary
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        WEB_URL=$$(gcloud run services describe ${_WEB_SERVICE} \
          --project=$PROJECT_ID --region=${_REGION} \
          --format='value(status.url)' --quiet 2>/dev/null || echo "")
        gcloud run deploy ${_API_SERVICE} \
          --project=$PROJECT_ID \
          --region=${_REGION} \
          --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_API_SERVICE}:$SHORT_SHA \
          --no-traffic \
          --tag=canary \
          --service-account=${_SA}@$PROJECT_ID.iam.gserviceaccount.com \
          --timeout=3600 \
          --allow-unauthenticated \
          --set-env-vars="GOOGLE_GENAI_USE_VERTEXAI=true,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=${_REGION}" \
          --set-env-vars="CORS_ORIGIN=https://oryn.seanesla.dev,$$WEB_URL" \
          --quiet
    waitFor: ['push-api']

  # ── 6. Deploy Web canary (no traffic) ──
  - id: deploy-web-canary
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - ${_WEB_SERVICE}
      - --project=$PROJECT_ID
      - --region=${_REGION}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_WEB_SERVICE}:$SHORT_SHA
      - --no-traffic
      - --tag=canary
      - --service-account=${_SA}@$PROJECT_ID.iam.gserviceaccount.com
      - --allow-unauthenticated
      - --quiet
    waitFor: ['push-web']

  # ── 7. Health-check API canary ──
  #    Use gcloud to resolve the tagged canary URL, then curl it.
  - id: healthcheck-api
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        CANARY_URL=$$(gcloud run services describe ${_API_SERVICE} \
          --project=$PROJECT_ID --region=${_REGION} \
          --format='value(status.traffic.url)' --quiet \
          | tr ';' '\n' | grep canary | head -1)
        if [ -z "$$CANARY_URL" ]; then
          echo "No canary tag URL found, using main URL"
          CANARY_URL=$$(gcloud run services describe ${_API_SERVICE} \
            --project=$PROJECT_ID --region=${_REGION} \
            --format='value(status.url)' --quiet)
        fi
        echo "Health-checking API at: $$CANARY_URL/health"
        curl -sSf --retry 4 --retry-delay 5 --retry-all-errors "$$CANARY_URL/health"
    waitFor: ['deploy-api-canary']

  # ── 8. Health-check Web canary ──
  - id: healthcheck-web
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        CANARY_URL=$$(gcloud run services describe ${_WEB_SERVICE} \
          --project=$PROJECT_ID --region=${_REGION} \
          --format='value(status.traffic.url)' --quiet \
          | tr ';' '\n' | grep canary | head -1)
        if [ -z "$$CANARY_URL" ]; then
          echo "No canary tag URL found, using main URL"
          CANARY_URL=$$(gcloud run services describe ${_WEB_SERVICE} \
            --project=$PROJECT_ID --region=${_REGION} \
            --format='value(status.url)' --quiet)
        fi
        echo "Health-checking Web at: $$CANARY_URL/"
        curl -sSf --retry 4 --retry-delay 5 --retry-all-errors "$$CANARY_URL/"
    waitFor: ['deploy-web-canary']

  # ── 9. Promote API — shift 100% traffic ──
  - id: promote-api
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - services
      - update-traffic
      - ${_API_SERVICE}
      - --project=$PROJECT_ID
      - --region=${_REGION}
      - --to-latest
      - --quiet
    waitFor: ['healthcheck-api']

  # ── 10. Promote Web — shift 100% traffic ──
  - id: promote-web
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - services
      - update-traffic
      - ${_WEB_SERVICE}
      - --project=$PROJECT_ID
      - --region=${_REGION}
      - --to-latest
      - --quiet
    waitFor: ['healthcheck-web']

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_API_SERVICE}:$SHORT_SHA
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_WEB_SERVICE}:$SHORT_SHA

timeout: 1800s
